### ISSUE TITLE
Swagger Spec

### ISSUE THREAD

**Issue by zanuka** [Encrypt-S/kauri-api#41]
- [x] write swagger spec for getrawtransactions POST
- [x] validate spec
- [x] publish on Swagger Hub
- [x] add to readme
- [x] add response / models to Swagger API
