### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by zanuka** [Encrypt-S/kauri-api#42]
## Strategy

**We will log in development / testnet only, not in production**

Logging can be expensive in Go without a good strategy. Resist the temptation of logging almost everything. Gather as much information as possible, and do it properly. Avoid the white noise of logs containing useless elements. Ensure that our logs report meaningful data that improves the overall health and longevity of the Kauri API app. 

## Tasks
- [ ] decide on log data shipper/catcher (Loggly, Logstash, Logmatic, etc...)
- [ ] configure log data shipper/catcher
- [ ] configure logs to report in dev / test only
- [ ] structure logs in JSON format
- [ ] log event types :: bind log output to specific line of code
- [ ] log output type :: JSON_PRETTY | JSON_ONELINE | DEBUG
- [ ] stream log data through TCP (SSL) using Logrus or something similar
- [ ] request key :: track requests across multiple services / daemons
